<?php if (false !== $data = $block->getDetailPushForward()): ?>
	<script type="text/javascript">
		<?php
		/**
		 * AdWords Dynamic Remarketing
		 */
		?>
		window.google_tag_params.ecomm_pagetype 	= '<?php echo $data->google_tag_params['ecomm_pagetype'] ?>';
		window.google_tag_params.ecomm_category 	= '<?php echo $data->google_tag_params['ecomm_category'] ?>';
		window.google_tag_params.ecomm_prodid		= '<?php echo $data->google_tag_params['ecomm_prodid'] ?>';
		window.google_tag_params.ecomm_totalvalue 	= '<?php echo $data->google_tag_params['ecomm_totalvalue'] ?>';
		<?php
		/**
		 * Detail push
		 */
		?>
		dataLayer.push(<?php echo $data->push ?>);
		<?php
		/**
		 * Grouped product map
		 */
		?>
		window.G = <?php echo $data->group ?>;

		<?php if ($block->getHelper()->facebook()): ?>

			if ("undefined" !== typeof fbq)
			{
				fbq('track', 'ViewContent', <?php echo $data->fbq ?>);
			}
			
		<?php endif ?>
	
	</script>
<?php endif ?>