<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'list';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_images_names_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = false;
    $showCompare = false;
    $showCart = false;
    $rating = false;
    $description = false;
}
?>
<?php if ($exist):
 $suffix = $block->getNameInLayout(); ?>
<div class="block widget block-viewed-products-<?php /* @escapeNotVerified */ echo $mode; ?>">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    
    
    <div class="owl-carousel owl-theme products-grid products-grid--max-6-col" id="owl-demo4">
         <?php foreach ($items as $_product): ?>
         <div class="item">
            <div class="product-image">
                  <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $block->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $block->getImage($_product, $image)->toHtml(); ?>
                 </a>
            </div>
            <div class="product_details">
                  <strong class="product-item-name">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $block->stripTags($_product->getName(), null, true) ?>"
                               class="product-item-link">
                                <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                 </strong>
                   <?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
                            $_product,
                            \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                            \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                            [
                                'price_id_suffix' => '-widget-viewed-' . $suffix
                            ]
                        ) ?>
                   
                    <div class="product-item-actions">
                      <?php if ($_product->isSaleable()): ?>
                      <div class="actions-primary">
                          <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                              <button class="action tocart primary"
                                      data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
                                      type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                  <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                              </button>
                          <?php else: ?>
                              <?php
                                  $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                  $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()]);
                              ?>
                              <button type="button" class="action tocart primary" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'>
                                  <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                              </button>
                          <?php endif; ?>
                      </div>
                      <?php else: ?>
                          <?php if ($_product->getIsSalable()): ?>
                              <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                          <?php else: ?>
                              <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                          <?php endif; ?>
                      <?php endif; ?>
                  </div>
            </div>
         </div>
         <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
        require(['jquery', 'owlcarousel'], function($,owlcarousel){
            $(function(){
            
              $('#owl-demo4').owlCarousel({
                    autoPlay: 3000,
                    navigation: true,
                    //navigationText: ["prev", "next"],
                     navigationText: false,
                    items : 1,
              });
            });
       });
    </script>
