<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storelocatorCollection = $objectManager->create('Agedcareandmedical\Storelocator\Model\Resource\Items\Collection');
$storelocatorCollection->load();

foreach($storelocatorCollection as $storelocator){
    $store_name = $storelocator->getStoreName();
    $store_address = $storelocator->getStoreAddress();
    $latitude = $storelocator->getLatitude();
    $longitude = $storelocator->getLongitude();
    $content = $store_name."<br>".$store_address;
    break;
}
?>

<div id="content" class="box_bg">
	<div id="post-1154" class="page post-1154 type-page status-publish hentry">
		<div id="mapConElem_1" class="gmp_map_opts ">
			<div id="gmpMapDetailsContainer_1" class="gmpMapDetailsContainer">
				<script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
				<div style='overflow:hidden;height:500px;width:1000px;'>
					<div id='gmap_canvas' style='height:700px;width:1000px;'>
					</div>
					
					<style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
				</div>
				<script type='text/javascript'>function init_map(){var myOptions = {zoom:4,center:new google.maps.LatLng(<?php echo $latitude;?>,<?php echo $longitude;?>),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(<?php echo $latitude;?>,<?php echo $longitude;?>)});infowindow = new google.maps.InfoWindow({content:'<?php echo $store_name;?>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
			</div>
			<h3>Stores</h3>
			<div id="gmpMapProControlsCon_1" class="gmpMapProControlsCon">
				<div id="gmapControlsNum_1" class="gmapMapsControls gmpSlideControls gmpViewTheme5">
					<div class="gmpMapsMarkersCategs">
						<div class="gmpMarkerTableSortingOpts">
							<div class="markersContainer gmpMarkersTable">
								<div>
									<div>
										<ul>
                                                                                    <?php foreach($storelocatorCollection as $storelocator){?>
											<li>
												<div class="gmpSliderTitleDescShell">
													<div class="openMarkerInMapShell">
                                                                                                            <input type="hidden" name="lat" class="lat" value="<?php echo $storelocator->getLatitude();?>" />
                                                                                                            <input type="hidden" name="long" class="long" value="<?php echo $storelocator->getLongitude();?>" />
                                                                                                            <input type="hidden" name="addr" class="addr" value="<?php echo $storelocator->getStoreName();?>" />
														<a class="openMarkerInMap" href="javascript:void(0)"><?php echo $storelocator->getStoreName();?></a>
													</div>
													<div class="description">
														<?php echo $storelocator->getStoreAddress();?>
													</div>
												</div>
											</li>
										    <?php }?>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery(".openMarkerInMapShell").on('click', function(){
                    var lat = jQuery(this).find(".lat").val();
                    var long = jQuery(this).find(".long").val();
                    var addr = jQuery(this).find(".addr").val();
                    
                    newLocation = new google.maps.LatLng(lat,long);
                    marker.setPosition( newLocation );
                    
                    //infowindow = new google.maps.InfoWindow
                    infowindow.setContent(addr);
	   });
	})
	
</script>

