<?php echo __('Module Ready')?>


<?php/*****
      *
      *1. One way Module colllection call.
      *
      *
***/ ?>



<?php 
/** @var \Agedcare\Brochure\Model\Resource\Items\Collection $brochureCollection */
   /*  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
     
     $brochureCollection = $objectManager->create('Agedcare\Brochure\Model\Resource\Items\Collection');
    
     $brochureCollection->load(); */

?>
<?php/*  foreach($brochureCollection as $brochure){
    
 echo "<pre>";print_r($brochure->getData());//echo 'Name  =  '.$brochure->getTitle().'<br>';
 

 
}*/ ?>

<?/***
   *
   *
   *2. Another Way module collection.
   *
   ***/?>

	

<?php /*$brochureCollection = $this->getBrochureCollection(); ?>

<?php foreach($brochureCollection as $brochure){
 echo "<pre>";print_r($brochure->getData());//echo $brochure->getTitle();
} */?>
